" General Settings
set list
set number
set cursorline
set nowrap
set tabstop=4 softtabstop=0 expandtab shiftwidth=4
set hlsearch
set colorcolumn=80,120

syntax on

hi ColorColumn ctermbg=lightgrey guibg=blue

"highlight ColorColumn ctermbg=0 guibg=lightgrey
"highlight ColorColumn ctermbg=1 guibg=lightgrey

" Turn off bell sound
set visualbell
set t_vb=
